job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: norway
    CONTAINER_PREFIX: planet4-norway
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-norway
    NEWRELIC_APPNAME: P4 Norway Development
    WP_DB_NAME: planet4-norway_wordpress_develop
    WP_STATELESS_BUCKET: planet4-norway-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: norway
    HELM_RELEASE: planet4-norway-release
    NEWRELIC_APPNAME: P4 Norway Release
    WP_DB_NAME: planet4-norway_wordpress_release
    WP_STATELESS_BUCKET: planet4-norway-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: norway
    HELM_RELEASE: planet4-norway-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Norway Production
    WP_DB_NAME: planet4-norway_wordpress_master
    WP_STATELESS_BUCKET: planet4-norway-stateless
